### ISSUE TITLE
let me filter statuses by author

### ISSUE THREAD

**Issue by daonb** [hasadna/kikar-hamedina#131]
HI,
I've been trying to find the API points I need for the election game and I came up short. I need a way to filter `facebook_status/` by the `feed` and better yet, by the `author_id` which seems to be missing.

**Comment by shygon** [comment]
Hey,
I added a `feed=<feed_id>` parameter to the facebook_status API parameter and it is currently in pull request #127.
It also includes a link from member to feed and from feed to member that can help navigate between feeds and MKs.
So e.g. this URL should work once the code is integrated: `/api/v1/facebook_status/?format=json&feed=14`

**Comment by yotammanor** [comment]
The pull request #127 was included, so now our code has that option in dev.
If all goes well it'll go to production today, as well.
