### ISSUE TITLE
Error when running vagrant reload --provision

### ISSUE THREAD

**Issue by elie222** [hasadna/kikar-hamedina#152]
==> default: Installed 10000 object(s) from 1 fixture(s)
==> default: Installed 10000 object(s) from 1 fixture(s)
==> default: Installed 10000 object(s) from 1 fixture(s)
==> default: Installed 8686 object(s) from 1 fixture(s)
==> default: Traceback (most recent call last):
==> default:   File "manage.py", line 10, in <module>
==> default:     execute_from_command_line(sys.argv)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
==> default:     utility.execute()
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
==> default:     self.fetch_command(subcommand).run_from_argv(self.argv)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
==> default:     self.execute(*args, **options.__dict__)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
==> default:
==> default: output = self.handle(*args, **options)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/loaddata.py", line 55, in handle
==> default:     self.loaddata(fixture_labels)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/loaddata.py", line 84, in loaddata
==> default:     self.load_label(fixture_label)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/loaddata.py", line 140, in load_label
==> default:     obj.save(using=self.using)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/core/serializers/base.py", line 164, in save
==> default:     models.Model.save_base(self.object, using=using, raw=True)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 573, in save_base
==> default:     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 635, in _save_table
==> default:     forced_update)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 679, in _do_update
==> default:     return filtered._update(values) > 0
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 507, in _update
==> default:     return query.get_compiler(self.db).execute_sql(None)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 975, in execute_sql
==> default:     cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 781, in execute_sql
==> default:     cursor.execute(sql, params)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 69, in execute
==> default:     return super(CursorDebugWrapper, self).execute(sql, params)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
==> default:     return self.cursor.execute(sql, params)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
==> default:     six.reraise(dj_exc_type, dj_exc_value, traceback)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
==> default:     return self.cursor.execute(sql, params)
==> default: django.db.utils.ProgrammingError: Problem installing fixture '/vagrant/kikar_hamedina/facebook_feeds/fixtures/1002_1005.json': Could not load facebook_feeds.Facebook_Status_Attachment(pk=1): column "source_width" of relation "facebook_feeds_facebook_status_attachment" does not exist
==> default: LINE 1: ..."type" = NULL, "picture" = NULL, "source" = NULL, "source_wi...
==> default:                                                              ^
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by yotammanor** [comment]
I'll fix it.

**Comment by yotammanor** [comment]
changed the vagrant file to exclude the problematic files for the moment.
works for me.

**Comment by yotammanor** [comment]
Fixed. solving locally might require some manage.py migrate facebook_feeds with flag --fake. talk to me for further help. rebooting should also work.
