### ISSUE TITLE
Add an API hook to receive the status by its FB unique ID

### ISSUE THREAD

**Issue by mushon** [hasadna/kikar-hamedina#155]
This should be pretty straight forward since if this url:
http://kikar.hasadna.org.il/status_permalink/335399036546914_793854937367986/

represents this url:
https://www.facebook.com/335399036546914/posts/793854937367986

The API could easily provide a JSON file for something along the lines of:
http://kikar.hasadna.org.il/API/?user=335399036546914&status=793854937367986
(or something like that)

@yotammanor does that make sense?
@nir-jackson would this be something you could work with?

**Comment by nir-jackson** [comment]
I could definitely work with that, that would be wonderful.

**Comment by nir-jackson** [comment]
This is my current facebook API call:
FB.api('/' + Post_ID, {access_token: accesstoken , feilds : "message"} ,function(response) {
   do stuff with the response.
}

**Comment by yotammanor** [comment]
Done, available at kikar.org/api/v1/facebook_status/?status_id=335399036546914_793854937367986
